# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rQf9vQqyRoiGtHH29fAqFIyxIA78TxYy
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from sklearn.preprocessing import RobustScaler
from pathlib import Path
from huggingface_hub import hf_hub_download
import os

REPO_ID = "MonyetttRindam/ckdbinary"

# ------------------------------------------------------------
# Konfigurasi halaman
# ------------------------------------------------------------
st.set_page_config(page_title="CKD Early Screening", layout="centered")
st.title("🧠 Skrining Awal Penyakit Ginjal Kronis (CKD)")
st.markdown("Isi data pasien berikut untuk mengetahui risiko CKD dan staging keparahan.")

# ------------------------------------------------------------
# Load model dan scaler

# ------------------------------------------------------------


@st.cache_resource
def load_models():
    # Unduh random forest model
    rf_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="random_forest_ckd.pkl"
    )
    model_binary = joblib.load(rf_path)

    # Unduh xgboost model
    xgb_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="xgboost_ckd.pkl"
    )
    model_multiclass = joblib.load(xgb_path)

    # Unduh scaler
    scaler_path = hf_hub_download(
        repo_id=REPO_ID,
        filename="scaler.pkl"
    )
    scaler = joblib.load(scaler_path)

    return model_binary, model_multiclass, scaler

# Panggil fungsi
try:
    model_binary, model_multiclass, scaler = load_models()
    st.success("✅ Model dan scaler berhasil dimuat dari Hugging Face Hub")
except Exception as e:
    st.error(f"Gagal memuat dari Hub: {e}")
    st.stop()

# ------------------------------------------------------------
# Fungsi preprocessing (mengikuti kode di laporan Word)
# ------------------------------------------------------------
def preprocess_input(data: pd.DataFrame) -> pd.DataFrame:
    """
    data: DataFrame dengan satu baris dan kolom sesuai input user.
    Mengembalikan DataFrame yang sudah diproses (siap untuk prediksi).
    """
    df = data.copy()

    # --------------------------------------------------------
    # 1. Replace nilai 7,9 menjadi NaN (sesuai kode training)
    #    Tapi karena input user sudah bersih, kita hanya pastikan tipe data
    # --------------------------------------------------------
    survey_cols = ['insulin_use', 'diabetes_pills', 'ever_smoked',
                   'current_smoker', 'diabetes_diagnosed', 'education_level']
    df[survey_cols] = df[survey_cols].replace([7, 9], np.nan)

    # --------------------------------------------------------
    # 2. Imputasi sederhana (asumsi user mengisi semua, tapi tetap ada fallback)
    # --------------------------------------------------------
    df['insulin_use'] = df['insulin_use'].fillna(0)
    df['diabetes_pills'] = df['diabetes_pills'].fillna(0)

    # Untuk lab dan bp: tidak ada imputasi berbasis target, user harus isi.
    # Jika masih NaN, isi dengan median global (nilai default)
    lab_bp_cols = ['phosphorus', 'bicarbonate', 'calcium', 'uric_acid',
                   'bp_systolic', 'bp_diastolic']
    for col in lab_bp_cols:
        df[col] = df[col].fillna(df[col].median())

    # --------------------------------------------------------
    # 3. Buat smoking_status dari ever_smoked & current_smoker
    # --------------------------------------------------------
    def create_smoking_status(row):
        ever = row['ever_smoked']
        current = row['current_smoker']
        if ever == 2:
            return 'never'
        elif ever == 1 and current == 1:
            return 'current'
        elif ever == 1 and current == 2:
            return 'former'
        return np.nan
    df['smoking_status'] = df.apply(create_smoking_status, axis=1)
    df.drop(columns=['ever_smoked', 'current_smoker'], inplace=True)

    # --------------------------------------------------------
    # 4. Buat age_group
    # --------------------------------------------------------
    def get_age_group(age):
        if age < 18:
            return 'child'
        elif age < 60:
            return 'adult'
        else:
            return 'elderly'
    df['age_group'] = df['age'].apply(get_age_group)

    # --------------------------------------------------------
    # 5. Imputasi body features (bmi, weight_kg, height_cm)
    #    Karena tidak punya grup median, kita isi dengan median global
    # --------------------------------------------------------
    for col in ['bmi', 'weight_kg', 'height_cm']:
        df[col] = df[col].fillna(df[col].median())

    # --------------------------------------------------------
    # 6. Imputasi education_level (mode global)
    # --------------------------------------------------------
    df['education_level'] = df['education_level'].fillna(df['education_level'].mode()[0])

    # --------------------------------------------------------
    # 7. Imputasi poverty_income_ratio (median global)
    # --------------------------------------------------------
    df['poverty_income_ratio'] = df['poverty_income_ratio'].fillna(df['poverty_income_ratio'].median())

    # --------------------------------------------------------
    # 8. Smoking status unknown
    # --------------------------------------------------------
    df['smoking_status'] = df['smoking_status'].fillna('unknown')

    # --------------------------------------------------------
    # 9. Buat MAP dan drop bp_systolic, bp_diastolic
    # --------------------------------------------------------
    df['MAP'] = (df['bp_systolic'] + 2 * df['bp_diastolic']) / 3
    df.drop(columns=['bp_systolic', 'bp_diastolic'], inplace=True)

    # --------------------------------------------------------
    # 10. Buat bmi_category
    # --------------------------------------------------------
    def bmi_category(bmi):
        if pd.isna(bmi):
            return np.nan
        if bmi < 18.5:
            return 'underweight'
        if bmi < 25.0:
            return 'normal'
        if bmi < 30.0:
            return 'overweight'
        return 'obese'
    df['bmi_category'] = df['bmi'].apply(bmi_category)

    # --------------------------------------------------------
    # 11. Drop weight_kg dan bmi (redundant)
    # --------------------------------------------------------
    df.drop(columns=['weight_kg', 'bmi'], inplace=True)

    # --------------------------------------------------------
    # 12. Ordinal encoding
    # --------------------------------------------------------
    education_order = [1, 2, 3, 4, 5]
    age_group_order = ['child', 'adult', 'elderly']
    bmi_order = ['underweight', 'normal', 'overweight', 'obese']
    smoking_order = ['never', 'unknown', 'former', 'current']

    ordinal_map = {
        'education_level': education_order,
        'age_group': age_group_order,
        'bmi_category': bmi_order,
        'smoking_status': smoking_order
    }
    for col, order in ordinal_map.items():
        mapping = {val: idx for idx, val in enumerate(order)}
        df[col] = df[col].map(mapping)

    # --------------------------------------------------------
    # 13. Binary encoding
    # --------------------------------------------------------
    df['gender'] = df['gender'].map({'Male': 0, 'Female': 1})
    # diabetes_diagnosed: 1=Yes -> 1, 2=No -> 0
    df['diabetes_diagnosed'] = df['diabetes_diagnosed'].map({1: 1, 2: 0})
    # insulin_use & diabetes_pills sudah 0/1, pastikan integer
    df['insulin_use'] = df['insulin_use'].astype(int)
    df['diabetes_pills'] = df['diabetes_pills'].astype(int)

    # --------------------------------------------------------
    # 14. One-hot encoding ethnicity (drop_first=True)
    # --------------------------------------------------------
    # Daftar ethnicity sesuai laporan
    ethnicity_categories = ['Non-Hispanic Asian', 'Non-Hispanic White', 'Other Hispanic',
                            'Other/Multiracial', 'Mexican American', 'Non-Hispanic Black']
    # Lakukan get_dummies, pastikan semua kategori muncul
    df = pd.get_dummies(df, columns=['ethnicity'], drop_first=True, dtype=int)
    # Tambahkan kolom yang mungkin hilang (jika ada kategori tidak muncul)
    for cat in ethnicity_categories[1:]:  # skip first
        col_name = f'ethnicity_{cat}'
        if col_name not in df.columns:
            df[col_name] = 0

    # --------------------------------------------------------
    # 15. Clipping sesuai clinical bounds
    # --------------------------------------------------------
    clinical_bounds = {
        'height_cm': (100.0, 210.0),
        'uric_acid': (1.5, 13.0),
        'calcium': (7.0, 12.0),
        'bicarbonate': (10.0, 40.0),
        'phosphorus': (1.0, 9.0),
    }
    for col, (low, high) in clinical_bounds.items():
        if col in df.columns:
            df[col] = df[col].clip(low, high)

    # --------------------------------------------------------
    # 16. Pastikan urutan kolom sama dengan training (pakai feature_names_in_ model)
    # --------------------------------------------------------
    expected_cols = model_binary.feature_names_in_  # RandomForest menyimpan nama kolom
    # Tambahkan kolom yang kurang, isi 0
    for col in expected_cols:
        if col not in df.columns:
            df[col] = 0
    # Urutkan sesuai urutan model
    df = df[expected_cols]

    # --------------------------------------------------------
    # 17. Scaling pada continuous_cols
    # --------------------------------------------------------
    continuous_cols = ['age', 'poverty_income_ratio', 'height_cm',
                       'phosphorus', 'bicarbonate', 'calcium',
                       'uric_acid', 'MAP']
    # Pastikan kolom ada
    for col in continuous_cols:
        if col not in df.columns:
            df[col] = 0
    df[continuous_cols] = scaler.transform(df[continuous_cols])

    return df

# ------------------------------------------------------------
# Form input data
# ------------------------------------------------------------
with st.form("input_form"):
    st.subheader("📋 Data Demografi & Klinis")

    col1, col2 = st.columns(2)
    with col1:
        age = st.number_input("Usia (tahun)", min_value=0, max_value=120, value=50, step=1)
        gender = st.selectbox("Jenis Kelamin", ["Male", "Female"])
        ethnicity = st.selectbox("Etnis", [
            "Non-Hispanic Asian", "Non-Hispanic White", "Other Hispanic",
            "Other/Multiracial", "Mexican American", "Non-Hispanic Black"
        ])
        education_level = st.selectbox("Tingkat Pendidikan (1-5)", [1,2,3,4,5], format_func=lambda x: {1:"Tidak tamat SD", 2:"SD", 3:"SMP", 4:"SMA", 5:"Perguruan Tinggi"}[x])
        poverty_income_ratio = st.number_input("Poverty Income Ratio (0-5)", min_value=0.0, max_value=5.0, value=1.5, step=0.1)

    with col2:
        height_cm = st.number_input("Tinggi badan (cm)", min_value=100.0, max_value=210.0, value=165.0, step=0.1)
        weight_kg = st.number_input("Berat badan (kg)", min_value=20.0, max_value=200.0, value=70.0, step=0.1)
        bmi = st.number_input("BMI (kg/m²)", min_value=10.0, max_value=50.0, value=24.0, step=0.1)
        bp_systolic = st.number_input("Tekanan darah sistolik (mmHg)", min_value=70, max_value=250, value=120, step=1)
        bp_diastolic = st.number_input("Tekanan darah diastolik (mmHg)", min_value=40, max_value=150, value=80, step=1)

    st.subheader("🧪 Hasil Laboratorium")
    col3, col4 = st.columns(2)
    with col3:
        phosphorus = st.number_input("Fosfor (mg/dL)", min_value=1.0, max_value=9.0, value=3.5, step=0.1)
        bicarbonate = st.number_input("Bikarbonat (mmol/L)", min_value=10.0, max_value=40.0, value=24.0, step=0.1)
        calcium = st.number_input("Kalsium (mg/dL)", min_value=7.0, max_value=12.0, value=9.0, step=0.1)
    with col4:
        uric_acid = st.number_input("Asam urat (mg/dL)", min_value=1.5, max_value=13.0, value=5.0, step=0.1)
        diabetes_diagnosed = st.selectbox("Diabetes didiagnosis?", [("Ya", 1), ("Tidak", 2)], format_func=lambda x: x[0])[1]
        insulin_use = st.selectbox("Penggunaan insulin", [("Ya", 1), ("Tidak", 0)], format_func=lambda x: x[0])[1]
        diabetes_pills = st.selectbox("Obat diabetes oral", [("Ya", 1), ("Tidak", 0)], format_func=lambda x: x[0])[1]

    st.subheader("🚬 Riwayat Merokok")
    col5, col6 = st.columns(2)
    with col5:
        ever_smoked = st.selectbox("Pernah merokok (minimal 100 batang seumur hidup)?", [("Ya", 1), ("Tidak", 2)], format_func=lambda x: x[0])[1]
    with col6:
        current_smoker = st.selectbox("Saat ini merokok?", [("Ya, setiap hari atau kadang", 1), ("Tidak, sudah berhenti", 2), ("Tidak pernah", 3)], format_func=lambda x: x[0])[1]

    submitted = st.form_submit_button("🔍 Lakukan Skrining")

# ------------------------------------------------------------
# Jika tombol ditekan, proses prediksi
# ------------------------------------------------------------
if submitted:
    # Buat DataFrame satu baris
    input_data = pd.DataFrame([{
        'age': age,
        'gender': gender,
        'ethnicity': ethnicity,
        'education_level': education_level,
        'poverty_income_ratio': poverty_income_ratio,
        'bmi': bmi,
        'weight_kg': weight_kg,
        'height_cm': height_cm,
        'bp_systolic': bp_systolic,
        'bp_diastolic': bp_diastolic,
        'phosphorus': phosphorus,
        'bicarbonate': bicarbonate,
        'calcium': calcium,
        'uric_acid': uric_acid,
        'diabetes_diagnosed': diabetes_diagnosed,
        'insulin_use': insulin_use,
        'diabetes_pills': diabetes_pills,
        'ever_smoked': ever_smoked,
        'current_smoker': current_smoker
    }])

    try:
        # Preprocessing
        X_processed = preprocess_input(input_data)

        # Prediksi binary (CKD atau tidak)
        pred_binary = model_binary.predict(X_processed)[0]

        st.subheader("📊 Hasil Skrining")
        if pred_binary == 0:
            st.success("✅ **TIDAK TERDETEKSI CKD** (Ginjal dalam kondisi normal)")
            st.balloons()
        else:
            st.error("⚠️ **TERDETEKSI CKD** - Risiko penyakit ginjal kronis")
            # Lanjut ke staging
            pred_stage = model_multiclass.predict(X_processed)[0]
            # Mapping staging: 0=bahaya, 1=cukup bahaya, 2=batas aman
            stage_map = {
                0: "🔴 **Bahaya** (Stadium lanjut, perlu penanganan segera)",
                1: "🟠 **Cukup Bahaya** (Stadium sedang, konsultasi nefrologi)",
                2: "🟢 **Batas Aman** (Stadium awal, modifikasi gaya hidup)"
            }
            st.markdown(f"### Staging Keparahan CKD: {stage_map[pred_stage]}")
            st.info("Segera konsultasikan hasil ini ke dokter spesialis ginjal untuk penanganan lebih lanjut.")

        # Tampilkan probabilitas? Tidak diminta, tapi bisa ditambahkan opsional
        # if st.checkbox("Tampilkan probabilitas prediksi"):
        #     proba = model_binary.predict_proba(X_processed)[0]
        #     st.write(f"Probabilitas CKD: {proba[1]:.2f}")

    except Exception as e:
        st.error(f"Terjadi kesalahan dalam pemrosesan data: {e}")
        st.write("Pastikan semua data terisi dengan benar dan model/scaler tersedia.")