# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y9WBK7tq8tUSaD1354xw65dlsTm8Jz-W
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import io

st.set_page_config(page_title="EDA Toolkit CKD", layout="wide")
st.title("📊 EDA Toolkit - Eksplorasi Dataset CKD")
st.markdown("Visualisasi interaktif dataset **sebelum dibersihkan** (raw data).")

# ------------------------------------------------------------
# Load dataset
# ------------------------------------------------------------
@st.cache_data
def load_data():
    df = pd.read_csv("ckd_dataset.csv")
    return df

try:
    df = load_data()
    st.success(f"✅ Dataset berhasil dimuat: {df.shape[0]} baris, {df.shape[1]} kolom")
except FileNotFoundError:
    st.error("❌ File 'ckd_dataset.csv' tidak ditemukan. Pastikan file ada di root repositori.")
    st.stop()

# ------------------------------------------------------------
# Sidebar: Filter dan pengaturan
# ------------------------------------------------------------
st.sidebar.header("⚙️ Pengaturan Visualisasi")

# Pilih jenis plot
plot_type = st.sidebar.selectbox(
    "📈 Pilih jenis grafik",
    ["📊 Bar Plot (Count)", "📦 Box Plot", "🥧 Pie Chart", "📉 Histogram", "📊 Bar Plot (Rata-rata)"]
)

# Deteksi tipe kolom
numeric_cols = df.select_dtypes(include=np.number).columns.tolist()
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

# Pilih kolom berdasarkan jenis plot
if plot_type in ["📊 Bar Plot (Count)", "🥧 Pie Chart"]:
    col = st.sidebar.selectbox("Pilih kolom kategorikal", categorical_cols)
elif plot_type in ["📦 Box Plot", "📉 Histogram"]:
    col = st.sidebar.selectbox("Pilih kolom numerik", numeric_cols)
elif plot_type == "📊 Bar Plot (Rata-rata)":
    col_cat = st.sidebar.selectbox("Pilih kolom kategorikal (sumbu X)", categorical_cols)
    col_num = st.sidebar.selectbox("Pilih kolom numerik (nilai rata-rata)", numeric_cols)

# ------------------------------------------------------------
# Plot
# ------------------------------------------------------------
if plot_type == "📊 Bar Plot (Count)":
    if col:
        freq = df[col].value_counts().reset_index()
        freq.columns = [col, "Frekuensi"]
        fig = px.bar(freq, x=col, y="Frekuensi", title=f"Distribusi {col}", color=col)
        st.plotly_chart(fig, use_container_width=True)

elif plot_type == "🥧 Pie Chart":
    if col:
        freq = df[col].value_counts()
        fig = px.pie(values=freq.values, names=freq.index, title=f"Proporsi {col}")
        st.plotly_chart(fig, use_container_width=True)

elif plot_type == "📦 Box Plot":
    if col:
        fig = px.box(df, y=col, title=f"Box Plot {col}", points="all")
        st.plotly_chart(fig, use_container_width=True)

elif plot_type == "📉 Histogram":
    if col:
        bins = st.sidebar.slider("Jumlah bins", 5, 100, 30)
        fig = px.histogram(df, x=col, nbins=bins, title=f"Histogram {col}")
        st.plotly_chart(fig, use_container_width=True)

elif plot_type == "📊 Bar Plot (Rata-rata)":
    if col_cat and col_num:
        mean_df = df.groupby(col_cat)[col_num].mean().reset_index()
        fig = px.bar(mean_df, x=col_cat, y=col_num, title=f"Rata-rata {col_num} per {col_cat}")
        st.plotly_chart(fig, use_container_width=True)

# ------------------------------------------------------------
# Tampilkan tabel data mentah
# ------------------------------------------------------------
st.subheader("📋 Dataset Mentah (Sebelum Pembersihan)")
st.dataframe(df.head(100))

# Opsional: ringkasan statistik
if st.checkbox("Lihat ringkasan statistik"):
    st.subheader("Deskripsi Statistik")
    st.dataframe(df.describe(include='all'))